name: segregation
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - numpy
  - scipy
  - warnings
  - pip
  - pip:
    - libpysal